const data = [
  {
    BatchNumber: 'BAT-001',
    BranchName: 'Training Batch A',
    Programme: 'Employee Onboarding Template',
    BatchDescription: 'Initial training for beginners',
    BatchStartDate: '01-01-2025',
    BatchEndDate: '01-15-2025',
    BatchStatus: 'Active',
    CreatedBy: 'Admin',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-002',
    BranchName: 'Advanced Workshop',
    Programme: 'Sales Report Template',
    BatchDescription: 'Advanced skills enhancement',
    BatchStartDate: '01-02-2025',
    BatchEndDate: '02-15-2025',
    BatchStatus: 'Active',
    CreatedBy: 'John Doe',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-003',
    BranchName: 'Technical Training',
    Programme: 'Marketing Campaign Brief',
    BatchDescription: 'Hands-on technical training',
    BatchStartDate: '01-03-2025',
    BatchEndDate: '03-20-2025',
    BatchStatus: 'Pending',
    CreatedBy: 'Jane Smith',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-004',
    BranchName: 'Leadership Program',
    Programme: 'Compliance Checklist Template',
    BatchDescription: 'Leadership skills development',
    BatchStartDate: '01-04-2025',
    BatchEndDate: '10-04-2025',
    BatchStatus: 'Completed',
    CreatedBy: 'Admin',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-005',
    BranchName: 'Onboarding Batch',
    Programme: 'Project Plan Template',
    BatchDescription: 'New employee onboarding',
    BatchStartDate: '01-05-2025',
    BatchEndDate: '05-15-2025',
    BatchStatus: 'Active',
    CreatedBy: 'HR Team',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-006',
    BranchName: 'Compliance Training',
    Programme: 'Invoice Template',
    BatchDescription: 'Regulatory compliance training',
    BatchStartDate: '01-06-2025',
    BatchEndDate: '10-06-2025',
    BatchStatus: 'Active',
    CreatedBy: 'ComplianceTeam',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-007',
    BranchName: 'Sales Mastery Program',
    Programme: 'Customer Feedback Form',
    BatchDescription: 'Advanced sales techniques',
    BatchStartDate: '01-07-2025',
    BatchEndDate: '07-20-2025',
    BatchStatus: 'Completed',
    CreatedBy: 'SalesLead',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-008',
    BranchName: 'Marketing Essentials',
    Programme: 'Technical Documentation Template',
    BatchDescription: 'Marketing fundamentals',
    BatchStartDate: '01-08-2025',
    BatchEndDate: '10-08-2025',
    BatchStatus: 'Active',
    CreatedBy: 'MarketingTeam',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-009',
    BranchName: 'Data Science Basics',
    Programme: 'Data Analysis Report Template',
    BatchDescription: 'Introduction to data science',
    BatchStartDate: '01-09-2025',
    BatchEndDate: '09-15-2025',
    BatchStatus: 'Active',
    CreatedBy: 'DataTeam',
    CreatedDate: '09-25-2025',
  },
  {
    BatchNumber: 'BAT-010',
    BranchName: 'Cloud Computing Bootcamp',
    Programme: 'Website Content Review Template',
    BatchDescription: 'Basics of cloud technologies',
    BatchStartDate: '01-10-2025',
    BatchEndDate: '10-10-2025',
    BatchStatus: 'Pending',
    CreatedBy: 'TechAdmin',
    CreatedDate: '09-25-2025',
  },
];
export default data;
